### ISSUE TITLE
Support loading environmental data from files and environment variables

### ISSUE THREAD

**Issue by Agares** [tremor-rs/tremor-runtime#1580]
**Describe the problem you are trying to solve**

Often it is needed to read tokens, or other static information and use it in pipelines. Currently there's no explicit support for such things (it's possible to do it with file/env connectors, but it's not a straightforward solution). 

**Describe the solution you'd like**
Simple syntax that allows providing static file contents or environment variables to pipelines.

**Notes**
Current solution (working, but seems unnecessarily complicated):
`pipes.yaml`:
```
onramp:
  - id: metronome
    type: metronome
    config:
      interval: 1000
  - id: secret
    type: file
    codec: string
    config:
        source: "/etc/tremor/sosecret"
offramp:
  - id: stdout-output # The unique id for binding/mapping
    type: stdout # The unique type descriptor for the offramp ( stdout here )
    codec: json # The underlying data format expected for application payload data
    config:
      prefix: ">> " # A prefix for data emitted on standard output by this offramp
binding:
  - id: pipeline # The unique name of this binding template
    links:
      "/onramp/secret/{instance}/out":
        - "/pipeline/pipeline/{instance}/file"
      "/onramp/metronome/{instance}/out": # Connect the input to the pipeline
        - "/pipeline/pipeline/{instance}/in"
      "/pipeline/pipeline/{instance}/out": # Connect the pipeline to the output
        - "/offramp/stdout-output/{instance}/in"
mapping:
  /binding/pipeline/01:
    instance: "01"
```
`pipeline.trickle`:
```
define script secretiser
script
    use std;
    use tremor;

    match tremor::origin::scheme() of
        case "tremor-file" => let state = {"secret": event}, drop
        default => {"secret": state.secret, "metronome_timestamp": event.ingest_ns, "id": event.id}
    end;
end;

create script secretiser;
create stream file;

select event from file into secretiser;

select event from in into secretiser;
select event from secretiser into out;
```
