### ISSUE TITLE
Better errors when a non existing codec is request

### ISSUE THREAD

**Issue by Licenser** [tremor-rs/tremor-runtime#488]
Currently when an onramp gets a codec that doesn't exist the user gets a stacktrace. This isn't nice, we need a better error.

```yaml
onramp:
  - id: http
    type: rest
    linked: true
    codec: strimg
    config:
      host: 0.0.0.0
      port: 8139
```
