### ISSUE TITLE
Investigate Introducing Peer/Transport

### ISSUE THREAD

**Issue by mfelsche** [tremor-rs/tremor-runtime#529]
**Describe the problem you are trying to solve**

In the [Linked Transport RFC](https://rfcs.tremor.rs/0003-linked-transports/#guide-level-explanation) we introduced the notion of a `Transport` entity. It encapsulates connection handling to an external entity and can act as sink or source and be referenced as such. Sinks and Sources referencing a transport should still configure how data is serialized with codecs and processors, the `Transport` will only handle its own outward connections and how serialized event data and not serialized metadata are turned into a `transport`-specific request or response or whatever.

When introducing linked transports we ended up reimplementing logic multiple times inside sinks and sources, that can be abstracted away into a proper framework for possibly linked sinks and sources and not have to reimplement it every time. Having such a `transport` or `peer` entity in the code would greatly simplify the code of linked transport implementations. Although it comes at the cost of maintaining another entity and all the shenanigans around it.

**Describe the solution you'd like**

We need to abstract over the sink and source nature of linked onramps/offramps and find a good framework for both avoiding boilerplate and providing meaningful interface to implementors and an intuitive way to configure these.

An example config defining a peer and referencing it as an onramp and as an offramp and bind it:

```yaml
peer:
  type: http-server
  id: my-rest-peer
  config:
    host: localhost
    port: 65535
onramp:
  id: http-onramp
  ref: "my-rest-peer"
  codec: json
  preprocessor: gzip
offramp:
  id: http-offramp
  ref: "my-rest-peer"
  codec: yaml
  preprocessor: xz

binding:
  id: binding01
  links:
    "/onramp/http-onramp/{instance}/out": ["/pipeline/bla/{instance}/in"]
    "/pipeline/bla/{instance}/out": ["/offramp/http-offramp/{instance}/in"]
```

This is only an initial suggestion and is open for changes.

**Comment by anupdhml** [comment]
If we want to avoid introducing (and maintaining) full new artefact for configuration, a scheme like below is a possibility:

```yaml
onramp:
  id: http-onramp
  type: rest
  codec: json
  preprocessor: gzip
  config:
    host: localhost
    port: 65535

offramp:
  id: http-offramp
  peer: "http-onramp"
  codec: yaml
  preprocessor: xz

binding:
  id: binding01
  links:
    "/onramp/http-onramp/{instance}/out": ["/pipeline/bla/{instance}/in"]
    "/pipeline/bla/{instance}/out": ["/offramp/http-offramp/{instance}/in"]
```

While this approach expresses the dependency between the artefacts better (`http-offramp` here won't work without the `http-onramp` and just using it is an error, but `http-onramp` can work independently), it comes with its own costs and problems.

Taking the above config as an example, we would now need to validate whether the connected `peer` is really an onramp and also of the right type that allows this kind of linking. Plus the peer nature of the underlying http server in use here is not immediately clear.

To minimize the latter issue in the codebase at least, we can still introduce `peer/http-server.rs` (plus `peer/http-client.rs`) -- parallel to `source/` and `sink/` with the new peer structs implementing both source and sink traits -- and `source/rest.rs` can just refer to the peer struct that implements source trait in `peer/http-server.rs` (this last strategy can be useful however we choose to expose the peer concept at the config level, to keep rest onramp working without referring to peers).
