### ISSUE TITLE
Invalid GELF header errors on valid gelf messages

### ISSUE THREAD

**Issue by anupdhml** [tremor-rs/tremor-runtime#626]
**Problem**

In v0.9.2, sending valid (unchunked) gelf messages results in them being rejected with `Invalid GELF header` errors.

This isn't an issue in v0.9.1. Brought to attention via @mattvaughan (thank you!).

**Steps**

```
onramp:
  - id: udp
    type: udp
    codec: json
    preprocessors:
      - decompress
      - gelf-chunking
      - decompress
    config:
      host: 127.0.0.1
      port: 8139

offramp:
  - id: console
    type: stdout

binding:
  - id: udp
    links:
      '/onramp/udp/{instance}/out':
        - "/pipeline/system::passthrough/system/in"

      "/pipeline/system::passthrough/system/out":
        - "/offramp/system::stdout/system/in"

mapping:
  /binding/udp/01:
    instance: "01"
```

Start tremor with (assuming above is saved in `config.yaml`):

```
cargo run -p tremor-cli -- server run -f ./config.yaml
```

Send a test gelf message:

```
echo -n '{"snot": "badger"}' | nc -u4 127.0.0.1 8139
```

Results in logs:
```
2020-12-01T15:07:12.593673258-05:00 ERROR tremor_runtime::preprocessor - [tremor://localhost/onramp/udp/01/out] Preprocessor [0] error Invalid GELF header len: 18, prefix: Some([123, 34])
2020-12-01T15:07:12.593800210-05:00 ERROR tremor_runtime::source - [Source::tremor://localhost/onramp/udp/01/out] Error decoding event data: Invalid GELF header len: 18, prefix: Some([123, 34])
```

**Possible Solution(s)**

Expand the pattern in https://github.com/tremor-rs/tremor-runtime/blob/v0.9.2/src/preprocessor/gelf.rs#L107 to cover payloads like the test one above.
