### ISSUE TITLE
Postprocessors not used by several sinks

### ISSUE THREAD

**Issue by mfelsche** [tremor-rs/tremor-runtime#632]
**Problem**

@mattvaughan discovered that the following sinks/offramps do not make use of postprocessors:

* stdout
* stderr
* udp

There are some special cases here that do not use postprocessors because of their internal message format requirements:
* elastic (writing the value directly to the request payload, which makes sense, as it needs to be json)
* newrelic 
* postgres

These need to be documented.

**Steps**
Configure a udp offramp like this:

```
offramp:
  - id: udp-out
    type: udp
    codec: json
    postprocessors:
      - gzip
      #- gelf-chunking # Tried this to no avail
    config:
      host: "0.0.0.0"
      port: 12203
      dst_host: "172.17.0.1" # Host machine IP from inside docker
      dst_port: 12201
```

and receive the output:

```
socat - UDP-LISTEN:12201 > logs.txt
cat logs.txt
```

**Possible Solution(s)**
Make use of the postprocessors. Simple as that!
