### ISSUE TITLE
Add support for line prefixes in stdout offramp

### ISSUE THREAD

**Issue by darach** [tremor-rs/tremor-runtime#83]
**Problem**

Configuring a prefix in the stdout offramp has no effect. The prefix is currently
ignored and this impacts the debugging/dev experience when developing new
pipelines/queries.

**Steps**

Add the following to the offramp configuration section for a passthrough pipeline:

```yaml
  - id: out
    type: stdout
    codec: json
    config:
      prefix: "Does-not-print> "
```

The prefix does not print as the beginning of every line as expected.

**Notes**

Output of `rustup --version`: 

```
rustup 1.21.1 (7832b2ebe 2019-12-20)
```

Output of `rustup show`:

```
stable-x86_64-apple-darwin (default)
rustc 1.41.0 (5e1a79984 2020-01-27)
```

Output of `tremor-server --version`: 

```
tremor version: 0.7.3
rd_kafka version: 0x000000ff, 1.3.0
tremor-runtime 0.7.3
```
